# Generated by Django 5.0 on 2023-12-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtoKaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=100)),
                ('groupId', models.CharField(blank=True, max_length=100, null=True)),
                ('taskDescription', models.CharField(max_length=500)),
                ('starred', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateCompleted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
